language: python
sudo: required
dist: xenial
python:
- '3.9'
- 3.8.3
- '3.8'
- '3.7'
- '3.6'
- '3.5'
before_install: sudo rm -f /etc/boto.cfg
install: make init
script:
- export BOTO_CONFIG=/dev/null
- make tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: TabxQrpjmYWabVDj1jhVTkFLtSYdvNFiq9OyeoMUCGE5sArIHDC44LGT7zxkYKO5u+x3rBB+H4cyyPJHFbliVqz6GPR8qgkop8uOOYDJD0o/6TueSyaYO2oxdpvNIEBQxgMIjUBWhN+9iq3tcNqGG9Suw9+f7WFJ95FidcrycFkXMuk9y3bqpTi2Vfun3pMyJuTCnkQdJB+daHW8wz3wkMSyeUkZR0jOAYgM6MvJVuuS8uY2iGtJ99qhYUCYAbdnljoMMlugJP422O06bi4kehyNZbRxvez+i1C+vD8Oa1Z8S193IMGuXuSHL+5jQ7IzI2kpw8lNBxS2xl0b+NYEGQzVW/0w/st3eCynehhBPh9mfjZovFqx4iMPwX/hGHf22bgUx3/hUJrnGDGu3HZf3hlAT6KTe74OHXoCyg0qVMQCW0Yslo6AZ2R19vUKEtt4zYk1Rnf2e2jLVdUWGudctINxjDNVVUeCpch3DCOQHjEFaVJHsi/7QAtIXvRMJOOdmYssmvTGNUaDa7n+ULT9sN81jSLdk9HcFVsA6diMvbStTHVMeaxXc+XydYi7wnQcUzDaaxV1sAn90HqFki/Bl7HOVaHU4X4lhgiTmDFx6eZgsu+iPLLICUUzdCYTWi2IEl77K9ZbS0qY2n4nF6HdKQ/RCSvf9nWTznxfrZHngE8=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
